# Mirroring OW open-watcom-v2 repository to SourceForge
#
# set secrets OWSFTOKEN1 - SSH user name
#             OWSFTOKEN2 - SSH password

name: Mirror

on: [push]

jobs:
  build:
    name: Mirror to SourceForge
    runs-on: ubuntu-latest
    steps:
    - name: OW Repo clone
      uses: actions/checkout@v1
    - name: Checkout master branch
      run: git checkout master
    - name: Prepare askpass script
      run: |
        echo "echo \"\$SSH_PASSWORD\"" > ~/askpass.sh
        chmod +x ~/askpass.sh
    - name: Mirror to SourceForge
      run: |
          mkdir ~/.ssh
          ssh-keyscan git.code.sf.net > ~/.ssh/known_hosts
          git push -v ssh://$OWSFUSER@git.code.sf.net/p/openwatcom/open-watcom-v2-test-jm
      env:
        OWSFUSER:     ${{ secrets.OWSFTOKEN1 }}
        SSH_PASSWORD: ${{ secrets.OWSFTOKEN2 }}
        SSH_ASKPASS:     ~/askpass.sh
        DISPLAY:         :0
        GIT_SSH_COMMAND: "setsid ssh"

