# Mirroring OW open-watcom-v2 repository to SourceForge
#
# set secrets OWSFTOKEN1 - SSH user name
#             OWSFTOKEN2 - SSH password

name: Mirror

on: [push]

jobs:
  build:
    name: Mirror to SourceForge
    runs-on: ubuntu-latest
    steps:
    - name: OW Repo clone
      uses: actions/checkout@v1
    - name: Checkout master branch
      run: git checkout master
    - name: Prepare askpass script
      run: |
        echo "echo \"\$SSH_PASSWORD\"" > $HOME/askpass.sh
        chmod +x $HOME/askpass.sh
    - name: Mirror to SourceForge
      run: |
          export SSH_ASKPASS=$HOME/askpass.sh
          mkdir $HOME/.ssh
          ssh-keyscan git.code.sf.net > $HOME/.ssh/known_hosts
          git push --force ssh://$OWSFUSER@git.code.sf.net/p/openwatcom/open-watcom-v2
      env:
        OWSFUSER:     ${{ secrets.OWSFTOKEN1 }}
        SSH_PASSWORD: ${{ secrets.OWSFTOKEN2 }}
        DISPLAY:         :0
        GIT_SSH_COMMAND: "setsid ssh"
